name: Build Index

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build Index.html
        run: |
          echo "" > .gitignore
          npm run build

      - uses: JamesIves/github-pages-deploy-action@v4.3.4
        name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        with:
          folder: cdnFiles # The folder the action should deploy.
